spring:
  application:
    name: crud

  datasource:
    url: jdbc:mysql://localhost:3307/crud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always # schema.sql 자동실행

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
