spring:
  application:
    name: crud

  datasource:
    url: jdbc:mysql://localhost:3307/crud
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always # data.sql 자동실행
